import { CategoryInfo, DocumentCategory } from '../types';

export const CATEGORIES: CategoryInfo[] = [
  {
    id: 'Bills',
    name: 'Bills',
    emoji: '🧾',
    color: '#8A5A00',
    bg: '#FFE9B8',
    borderColor: '#F3D389',
    count: 24,
    aiPrompt: 'Electricity, water, Wi-Fi, phone recharges, credit card statements and utility payments.',
    isCustom: false,
  },
  {
    id: 'Vehicle',
    name: 'Vehicle',
    emoji: '🚗',
    color: '#0F6AA8',
    bg: '#D7EEFF',
    borderColor: '#AAD8F5',
    count: 8,
    aiPrompt: 'Vehicle registration (RC), driving licence, car/bike servicing invoices, and pollution certificates.',
    isCustom: false,
  },
  {
    id: 'Finance',
    name: 'Finance',
    emoji: '🏦',
    color: '#0B7A50',
    bg: '#D6F5E3',
    borderColor: '#A6E6C3',
    count: 18,
    aiPrompt: 'Bank statements, investment summaries, mutual funds, tax returns (ITR), and loan documents.',
    isCustom: false,
  },
  {
    id: 'Home',
    name: 'Home',
    emoji: '🏠',
    color: '#C2471F',
    bg: '#FFE0D6',
    borderColor: '#F7BDA9',
    count: 12,
    aiPrompt: 'Rental agreements, maintenance receipts, property taxes, registry papers, and lease deeds.',
    isCustom: false,
  },
  {
    id: 'Insurance',
    name: 'Insurance',
    emoji: '🛡️',
    color: '#5B4BC4',
    bg: '#E8E1FF',
    borderColor: '#DCD3F8',
    count: 6,
    aiPrompt: 'Health, term life, vehicle insurance policies, claim documents, and premium renewal notices.',
    isCustom: false,
  },
  {
    id: 'Purchases',
    name: 'Purchases',
    emoji: '🛒',
    color: '#8A5A00',
    bg: '#FFE9B8',
    borderColor: '#F3D389',
    count: 7,
    aiPrompt: 'Retail store receipts, online e-commerce invoices, electronics warranty slips, and gadget guarantees.',
    isCustom: false,
  },
  {
    id: 'Other',
    name: 'Other',
    emoji: '📦',
    color: '#6E8078',
    bg: '#EFEAD9',
    borderColor: '#E0CFA5',
    count: 9,
    aiPrompt: 'General personal documents, identification certificates, and uncategorised paperwork.',
    isCustom: false,
  },
];

export const CATEGORY_PICK_LIST: [string, DocumentCategory][] = [
  ['🧾', 'Bills'],
  ['🏦', 'Finance'],
  ['🚗', 'Vehicle'],
  ['🏠', 'Home'],
  ['🛡️', 'Insurance'],
  ['🛒', 'Purchases'],
  ['📦', 'Other'],
];
